<a href="https://colab.research.google.com/github/pradhiksha2000/day1_ds/blob/main/Day1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**implementing numpy using python programming**

In [5]:
#importing libraries
import numpy as np

a = [1,2,3,4]#list

arr1 = np.array(a)
print(arr1)

b =[[1,2,3,4],[4,5,6,7]]#list2

arr2 = np.array(b)
print(arr2)

[1 2 3 4]
[[1 2 3 4]
 [4 5 6 7]]


In [18]:
import sys

s = np.arange(10000)

print("size of each element numpy array in bytes",s.itemsize)
print("size of whole array in bytes:", s.size * s.itemsize)

size of each element numpy array in bytes 8
size of whole array in bytes: 80000


In [10]:
import numpy as np
import time

a = range(10000)
b = range(10000)

start = time.time() #mark the start time
#list comprehension (multiply each element of a and b)

ab = [(a *b) for a,b in zip(a,b)]

end = time.time()

print("total time taken:", end - start)

total time taken: 0.002444028854370117


In [11]:
import numpy as np
arr3 = np.array([[1,2,3], [4,5,6]], ndmin = 2)

print(arr3) 

[[1 2 3]
 [4 5 6]]


In [12]:
arr4 = np.array([[1,2,3],[4,5,6]])

print(arr4.dtype)
printarr4.ndim
printarr4.shape
printarr4.size

6

In [14]:
zero1 = np.zeros((2,2))

print(zero1)

[[0. 0.]
 [0. 0.]]


In [16]:
import numpy as np
c = np.arange(3,10,2)

print(type(c))

<class 'numpy.ndarray'>


In [19]:
a = [1,2,3,4,5]

b = np.array(a)

print(b)



[1 2 3 4 5]


In [20]:
b[-2]

4

In [22]:
b[0:1]

array([1])

In [24]:
b[0] = 10

print(b)

[10  2  3  4  5]


In [26]:
print(b[2:])

[3 4 5]


In [27]:
print(b[ :3])

[10  2  3]


In [ ]:
c = np.array([[1,2,3,4,5], [6,7,8,9,10]])
c



**pandas library implementation**

In [29]:
import pandas as pd

dataset = pd.read_csv("/content/sample_data/california_housing_test.csv")

In [31]:
dataset.head(15)

longitude  latitude  ...  median_income  median_house_value
0     -122.05     37.37  ...         6.6085            344700.0
1     -118.30     34.26  ...         3.5990            176500.0
2     -117.81     33.78  ...         5.7934            270500.0
3     -118.36     33.82  ...         6.1359            330000.0
4     -119.67     36.33  ...         2.9375             81700.0
5     -119.56     36.51  ...         1.6635             67000.0
6     -121.43     38.63  ...         1.6641             67000.0
7     -120.65     35.48  ...         3.2250            166900.0
8     -122.84     38.40  ...         3.6696            194400.0
9     -118.02     34.08  ...         2.3333            164200.0
10    -118.24     33.98  ...         2.2054            125000.0
11    -119.12     35.85  ...         2.4167             58300.0
12    -121.93     37.25  ...         4.6900            252600.0
13    -117.03     32.97  ...         4.5625            231200.0
14    -117.97     33.73  ...         5.7121            222500.0

[15 rows x 9 columns]

In [32]:
dataset.shape


(3000, 9)

In [33]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB


In [35]:

dataset.describe()

longitude    latitude  ...  median_income  median_house_value
count  3000.000000  3000.00000  ...    3000.000000          3000.00000
mean   -119.589200    35.63539  ...       3.807272        205846.27500
std       1.994936     2.12967  ...       1.854512        113119.68747
min    -124.180000    32.56000  ...       0.499900         22500.00000
25%    -121.810000    33.93000  ...       2.544000        121200.00000
50%    -118.485000    34.27000  ...       3.487150        177650.00000
75%    -118.020000    37.69000  ...       4.656475        263975.00000
max    -114.490000    41.92000  ...      15.000100        500001.00000

[8 rows x 9 columns]

In [36]:
dataset1 = pd.read_html('https://en.wikipedia.org/wiki/Data_science#:~:text=Data%20science%20is%20an%20interdisciplinary,broad%20range%20of%20application%20domains.') [3]
dataset.head()

IndexError: ignored